version: '3'

services:
  mongo:
    image: mongo
    environment:
        - MONGO_INITDB_DATABASE=cogent
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db

  redis-queue:
    image: redis:6.2-alpine
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    restart: always
    ports:
      - '6379:6379'
    command: redis-server
    volumes: 
      - redis:/data

  server:
    image: cogent-server
    build:
      context: server
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=dev
      - MONGODB_URI=mongodb://mongo:27017/cogent
      - REDIS_URI=redis://redis-queue:6379
    depends_on:
      - mongo
      - redis-queue
    ports:
      - "5000:5000"
    volumes:
      - ./server/uploads:/usr/src/app/uploads
      - ./server/thumbnails:/usr/src/app/thumbnails

  web_app:
    image: cogent-webapp
    build:
      context: web_app
      dockerfile: ./Dockerfile
    environment:
      - API_HOST=http://localhost:5000/api
    ports:
      - "3000:3000" 

volumes:
  mongo:
    driver: local
  redis:
    driver: local